export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/project.emergencybangladesh/",
  facebook: "https://www.facebook.com/Project.EmergencyBanglaDesh",
  github: "http://github.com/emergency-bangladesh",
  linkedin: "https://www.linkedin.com/company/project-emergency-bangladesh/",
};

export const DISTRICT_WITH_UPAZILA_OR_THANA: Array<{
  name: string;
  allUpazilaOrThana: Array<string>;
}> = [
  {
    name: "Bagerhat",
    allUpazilaOrThana: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
  },
  {
    name: "Bandarban",
    allUpazilaOrThana: [
      "Bandarban Sadar",
      "Alikadam",
      "Lama",
      "Naikhongchhari",
      "Rowangchhari",
      "Ruma",
      "Thanchi",
    ],
  },
  {
    name: "Barguna",
    allUpazilaOrThana: [
      "Barguna Sadar",
      "Amtali",
      "Betagi",
      "Bamna",
      "Patharghata",
      "Taltali",
    ],
  },
  {
    name: "Barishal",
    allUpazilaOrThana: [
      "Barishal Sadar",
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
    ],
  },
  {
    name: "Bhola",
    allUpazilaOrThana: [
      "Bhola Sadar",
      "Borhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
  },
  {
    name: "Bogura",
    allUpazilaOrThana: [
      "Bogura Sadar",
      "Adamdighi",
      "Dhunot",
      "Gabtali",
      "Kahaloo",
      "Nandigram",
      "Sariakandi",
      "Sherpur",
      "Shibganj",
      "Sonatala",
      "Dupchanchia",
      "Shajahanpur",
    ],
  },
  {
    name: "Brahmanbaria",
    allUpazilaOrThana: [
      "Brahmanbaria Sadar",
      "Akhaura",
      "Ashuganj",
      "Bancharampur",
      "Bijoynagar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
    ],
  },
  {
    name: "Chandpur",
    allUpazilaOrThana: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Haziganj",
      "Kachua",
      "Matlab Dakshin",
      "Matlab Uttar",
      "Shahrasti",
    ],
  },
  {
    name: "Chattogram",
    allUpazilaOrThana: [
      "Pahartali",
      "Patenga",
      "Bandar",
      "Bakalia",
      "Bayazid",
      "Chandgaon",
      "Chawkbazar",
      "Kotwali",
      "Halishahar",
      "Khulshi",
      "Akbar Shah",
      "Double Mooring",
      "Panchlaish",
      "Anowara",
      "Banskhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
    ],
  },
  {
    name: "Chuadanga",
    allUpazilaOrThana: [
      "Chuadanga Sadar",
      "Alamdanga",
      "Damurhuda",
      "Jibannagar",
    ],
  },
  {
    name: "Cox's Bazar",
    allUpazilaOrThana: [
      "Cox's Bazar Sadar",
      "Chakaria",
      "Kutubdia",
      "Maheshkhali",
      "Pekua",
      "Ramu",
      "Teknaf",
      "Ukhia",
    ],
  },
  {
    name: "Cumilla",
    allUpazilaOrThana: [
      "Cumilla Adarsha Sadar",
      "Burichong",
      "Brahmanpara",
      "Chandina",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Laksam",
      "Muradnagar",
      "Nangalkot",
      "Titas",
      "Meghna",
      "Monohorganj",
      "Sadakpur",
      "Barura",
      "Chauddagram",
    ],
  },
  {
    name: "Dhaka",
    allUpazilaOrThana: [
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
      "Dhaka Cantonment",
      "Adabor",
      "Badda",
      "Bangshal",
      "Bimanbandar",
      "Cantonment",
      "Chawkbazar",
      "Dakshinkhan",
      "Darus Salam",
      "Demra",
      "Dhanmondi",
      "Gendaria",
      "Gulshan",
      "Hazaribagh",
      "Jatrabari",
      "Kadamtali",
      "Kafrul",
      "Kalabagan",
      "Khilgaon",
      "Khilkhet",
      "Lalbagh",
      "Mirpur",
      "Mohammadpur",
      "Motijheel",
      "Mugda",
      "New Market",
      "Pallabi",
      "Paltan",
      "Ramna",
      "Rampura",
      "Rupnagar",
      "Sabujbagh",
      "Shah Ali",
      "Shahbagh",
      "Sher-e-Bangla Nagar",
      "Shyampur",
      "Sutrapur",
      "Tejgaon",
      "Turag",
      "Uttara",
      "Uttarkhan",
      "Vatara",
    ],
  },
  {
    name: "Dinajpur",
    allUpazilaOrThana: [
      "Dinajpur Sadar",
      "Birampur",
      "Birganj",
      "Bochaganj",
      "Fulbari",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Chirirbandar",
      "Parbatipur",
      "Nawabganj",
      "Biral",
    ],
  },
  {
    name: "Faridpur",
    allUpazilaOrThana: [
      "Faridpur Sadar",
      "Alfadanga",
      "Bhanga",
      "Boalmari",
      "Charbhadrasan",
      "Madhukhali",
      "Nagarkanda",
      "Sadarpur",
      "Shaltha",
    ],
  },
  {
    name: "Feni",
    allUpazilaOrThana: [
      "Feni Sadar",
      "Chhagalnaiya",
      "Daganbhuiyan",
      "Fulgazi",
      "Parshuram",
      "Sonagazi",
    ],
  },
  {
    name: "Gaibandha",
    allUpazilaOrThana: [
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Phulchhari",
      "Sadullapur",
      "Saghata",
      "Sundarganj",
    ],
  },
  {
    name: "Gazipur",
    allUpazilaOrThana: [
      "Gazipur Sadar",
      "Kaliakair",
      "Kaliganj",
      "Kapasia",
      "Sreepur",
    ],
  },
  {
    name: "Gopalganj",
    allUpazilaOrThana: [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Muksudpur",
      "Tungipara",
    ],
  },
  {
    name: "Habiganj",
    allUpazilaOrThana: [
      "Habiganj Sadar",
      "Ajmiriganj",
      "Bahubal",
      "Baniachong",
      "Chunarughat",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
      "Shaistaganj",
    ],
  },
  {
    name: "Jamalpur",
    allUpazilaOrThana: [
      "Jamalpur Sadar",
      "Baksiganj",
      "Dewanganj",
      "Islampur",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
    ],
  },
  {
    name: "Jashore",
    allUpazilaOrThana: [
      "Jashore Sadar",
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Jhikargachha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
  },
  {
    name: "Jhalokati",
    allUpazilaOrThana: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  {
    name: "Jhenaidah",
    allUpazilaOrThana: [
      "Jhenaidah Sadar",
      "Harinkunda",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
      "Shailkupa",
    ],
  },
  {
    name: "Joypurhat",
    allUpazilaOrThana: [
      "Joypurhat Sadar",
      "Akkelpur",
      "Kalai",
      "Khetlal",
      "Panchbibi",
    ],
  },
  {
    name: "Khagrachari",
    allUpazilaOrThana: [
      "Khagrachari Sadar",
      "Dighinala",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Panchhari",
      "Ramgarh",
      "Matiranga",
    ],
  },
  {
    name: "Khulna",
    allUpazilaOrThana: [
      "Khulna Sadar",
      "Batiaghata",
      "Dacope",
      "Daulatpur",
      "Dighalia",
      "Dumuria",
      "Fultala",
      "Khalishpur",
      "Khan Jahan Ali",
      "Koyra",
      "Paikgachha",
      "Rupsa",
      "Sonadanga",
    ],
  },
  {
    name: "Kishoreganj",
    allUpazilaOrThana: [
      "Kishoreganj Sadar",
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
      "Hossainpur",
    ],
  },
  {
    name: "Kurigram",
    allUpazilaOrThana: [
      "Kurigram Sadar",
      "Bhurungamari",
      "Chilmari",
      "Phulbari",
      "Rajarhat",
      "Raumari",
      "Nageshwari",
      "Ulipur",
      "Char Rajibpur",
    ],
  },
  {
    name: "Kushtia",
    allUpazilaOrThana: [
      "Kushtia Sadar",
      "Bheramara",
      "Daulatpur",
      "Khoksa",
      "Kumarkhali",
      "Mirpur",
    ],
  },
  {
    name: "Lalmonirhat",
    allUpazilaOrThana: [
      "Lalmonirhat Sadar",
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Patgram",
    ],
  },
  {
    name: "Madaripur",
    allUpazilaOrThana: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],
  },
  {
    name: "Magura",
    allUpazilaOrThana: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  },
  {
    name: "Manikganj",
    allUpazilaOrThana: [
      "Manikganj Sadar",
      "Daulatpur",
      "Ghior",
      "Harirampur",
      "Saturia",
      "Shibalaya",
      "Singair",
    ],
  },
  {
    name: "Meherpur",
    allUpazilaOrThana: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  },
  {
    name: "Moulvibazar",
    allUpazilaOrThana: [
      "Moulvibazar Sadar",
      "Barlekha",
      "Juri",
      "Kamalganj",
      "Kulaura",
      "Rajnagar",
      "Sreemangal",
    ],
  },
  {
    name: "Munshiganj",
    allUpazilaOrThana: [
      "Munshiganj Sadar",
      "Gazaria",
      "Lohajang",
      "Sirajdikhan",
      "Sreenagar",
      "Tongibari",
    ],
  },
  {
    name: "Mymensingh",
    allUpazilaOrThana: [
      "Mymensingh Sadar",
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gauripur",
      "Haluaghat",
      "Ishwarganj",
      "Muktagachha",
      "Nandail",
      "Phulpur",
      "Trishal",
      "Tarakanda",
    ],
  },
  {
    name: "Naogaon",
    allUpazilaOrThana: [
      "Naogaon Sadar",
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Mahadevpur",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
  },
  {
    name: "Narail",
    allUpazilaOrThana: ["Narail Sadar", "Lohagara", "Kalia"],
  },
  {
    name: "Narayanganj",
    allUpazilaOrThana: [
      "Narayanganj Sadar",
      "Araihazar",
      "Bandar",
      "Fatullah",
      "Rupganj",
      "Sonargaon",
    ],
  },
  {
    name: "Narsingdi",
    allUpazilaOrThana: [
      "Narsingdi Sadar",
      "Belabo",
      "Monohardi",
      "Palash",
      "Raipura",
      "Shibpur",
    ],
  },
  {
    name: "Natore",
    allUpazilaOrThana: [
      "Natore Sadar",
      "Bagatipara",
      "Baraigram",
      "Gurudaspur",
      "Lalpur",
      "Singra",
      "Naldanga",
    ],
  },
  {
    name: "Netrokona",
    allUpazilaOrThana: [
      "Netrokona Sadar",
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Kalmakanda",
      "Kendua",
      "Khaliajuri",
      "Madan",
      "Mohanganj",
      "Purbadhala",
    ],
  },
  {
    name: "Nilphamari",
    allUpazilaOrThana: [
      "Nilphamari Sadar",
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishoreganj",
      "Saidpur",
    ],
  },
  {
    name: "Noakhali",
    allUpazilaOrThana: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Hatiya",
      "Kobirhat",
      "Senbagh",
      "Sonaimuri",
      "Subarnachar",
      "Companiganj",
    ],
  },
  {
    name: "Pabna",
    allUpazilaOrThana: [
      "Pabna Sadar",
      "Atgharia",
      "Bera",
      "Bhangura",
      "Faridpur",
      "Ishwardi",
      "Santhia",
      "Sujanagar",
      "Chatmohar",
    ],
  },
  {
    name: "Panchagarh",
    allUpazilaOrThana: [
      "Panchagarh Sadar",
      "Atwari",
      "Boda",
      "Debiganj",
      "Tetulia",
    ],
  },
  {
    name: "Patuakhali",
    allUpazilaOrThana: [
      "Patuakhali Sadar",
      "Bauphal",
      "Dashmina",
      "Galachipa",
      "Kalapara",
      "Mirzaganj",
      "Dumki",
      "Rangabali",
    ],
  },
  {
    name: "Pirojpur",
    allUpazilaOrThana: [
      "Pirojpur Sadar",
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Nesarabad",
      "Zianagar",
    ],
  },
  {
    name: "Rajbari",
    allUpazilaOrThana: [
      "Rajbari Sadar",
      "Baliakandi",
      "Goalandaghat",
      "Pangsha",
      "Kalukhali",
    ],
  },
  {
    name: "Rajshahi",
    allUpazilaOrThana: [
      "Rajshahi Sadar",
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Putia",
      "Tanore",
    ],
  },
  {
    name: "Rangamati",
    allUpazilaOrThana: [
      "Rangamati Sadar",
      "Bagaichhari",
      "Barkal",
      "Belaichhari",
      "Kaptai",
      "Juraichhari",
      "Langadu",
      "Naniarchar",
      "Rajasthali",
      "Kawkhali",
    ],
  },
  {
    name: "Rangpur",
    allUpazilaOrThana: [
      "Rangpur Sadar",
      "Badarganj",
      "Gangachara",
      "Kaunia",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Taraganj",
    ],
  },
  {
    name: "Satkhira",
    allUpazilaOrThana: [
      "Satkhira Sadar",
      "Assasuni",
      "Debhata",
      "Kaliganj",
      "Kalaroa",
      "Shyamnagar",
      "Tala",
    ],
  },
  {
    name: "Shariatpur",
    allUpazilaOrThana: [
      "Shariatpur Sadar",
      "Damudya",
      "Gosairhat",
      "Naria",
      "Jajira",
      "Bhedarganj",
    ],
  },
  {
    name: "Sherpur",
    allUpazilaOrThana: [
      "Sherpur Sadar",
      "Nalitabari",
      "Jhenaigati",
      "Nakla",
      "Sreebardi",
    ],
  },
  {
    name: "Sirajganj",
    allUpazilaOrThana: [
      "Sirajganj Sadar",
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahzadpur",
      "Tarash",
      "Ullahpara",
    ],
  },
  {
    name: "Sunamganj",
    allUpazilaOrThana: [
      "Sunamganj Sadar",
      "Bishwamvarpur",
      "Chhatak",
      "Derai",
      "Dharmapasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Sulla",
      "Tahirpur",
      "South Sunamganj",
    ],
  },
  {
    name: "Sylhet",
    allUpazilaOrThana: [
      "Sylhet Sadar",
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Jakiganj",
      "South Surma",
    ],
  },
  {
    name: "Tangail",
    allUpazilaOrThana: [
      "Tangail Sadar",
      "Basail",
      "Bhuapur",
      "Delduar",
      "Ghatail",
      "Gopalpur",
      "Kalihati",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
      "Dhanbari",
    ],
  },
  {
    name: "Thakurgaon",
    allUpazilaOrThana: [
      "Thakurgaon Sadar",
      "Baliadangi",
      "Haripur",
      "Pirganj",
      "Ranisankail",
    ],
  },
];
