/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationIndexRouteImport } from './routes/registration/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as VolunteerUuidRouteImport } from './routes/volunteer/$uuid'
import { Route as TeamCreateRouteImport } from './routes/team/create'
import { Route as TeamUuidRouteImport } from './routes/team/$uuid'
import { Route as SettingsUpdateInformationRouteImport } from './routes/settings/update-information'
import { Route as SettingsChangePasswordRouteImport } from './routes/settings/change-password'
import { Route as RegistrationSuccessRouteImport } from './routes/registration/success'
import { Route as IssuesUuidRouteImport } from './routes/issues/$uuid'
import { Route as staticFaqRouteImport } from './routes/(static)/faq'
import { Route as staticContactUsRouteImport } from './routes/(static)/contact-us'
import { Route as staticAboutUsRouteImport } from './routes/(static)/about-us'
import { Route as RegistrationVolunteerLayoutRouteImport } from './routes/registration/volunteer/_layout'
import { Route as IssuesNewIndexRouteImport } from './routes/issues/new/index'
import { Route as staticLegalIndexRouteImport } from './routes/(static)/legal/index'
import { Route as VolunteerUploadMissingMediaUuidRouteImport } from './routes/volunteer/upload-missing-media.$uuid'
import { Route as RegistrationVolunteerUploadProfilePictureRouteImport } from './routes/registration/volunteer/upload-profile-picture'
import { Route as RegistrationVolunteerSetPasswordRouteImport } from './routes/registration/volunteer/set-password'
import { Route as RegistrationVolunteerSelectIdTypeRouteImport } from './routes/registration/volunteer/select-id-type'
import { Route as RegistrationVolunteerPersonalInformationRouteImport } from './routes/registration/volunteer/personal-information'
import { Route as RegistrationVolunteerNidInformationRouteImport } from './routes/registration/volunteer/nid-information'
import { Route as RegistrationVolunteerLocationInformationRouteImport } from './routes/registration/volunteer/location-information'
import { Route as RegistrationVolunteerBrnInformationRouteImport } from './routes/registration/volunteer/brn-information'
import { Route as staticLegalWhyWeRequireIdDocumentsRouteImport } from './routes/(static)/legal/why-we-require-id-documents'
import { Route as staticLegalTermsAndConditionsRouteImport } from './routes/(static)/legal/terms-and-conditions'
import { Route as staticLegalPrivacyPolicyRouteImport } from './routes/(static)/legal/privacy-policy'
import { Route as IssuesNewLostAndFoundLayoutRouteImport } from './routes/issues/new/lost-and-found/_layout'
import { Route as IssuesNewBloodDonationLayoutRouteImport } from './routes/issues/new/blood-donation/_layout'
import { Route as IssuesNewLostAndFoundAddMoreInformationRouteImport } from './routes/issues/new/lost-and-found/add-more-information'
import { Route as IssuesNewLostAndFoundAddImagesRouteImport } from './routes/issues/new/lost-and-found/add-images'
import { Route as IssuesNewLostAndFoundAddContactInformationRouteImport } from './routes/issues/new/lost-and-found/add-contact-information'
import { Route as IssuesNewLostAndFoundAddBasicInformationRouteImport } from './routes/issues/new/lost-and-found/add-basic-information'
import { Route as IssuesNewBloodDonationAddLocationInformationRouteImport } from './routes/issues/new/blood-donation/add-location-information'
import { Route as IssuesNewBloodDonationAddContactInformationRouteImport } from './routes/issues/new/blood-donation/add-contact-information'
import { Route as IssuesNewBloodDonationAddBasicInformationRouteImport } from './routes/issues/new/blood-donation/add-basic-information'

const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerUuidRoute = VolunteerUuidRouteImport.update({
  id: '/volunteer/$uuid',
  path: '/volunteer/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCreateRoute = TeamCreateRouteImport.update({
  id: '/team/create',
  path: '/team/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUuidRoute = TeamUuidRouteImport.update({
  id: '/team/$uuid',
  path: '/team/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUpdateInformationRoute =
  SettingsUpdateInformationRouteImport.update({
    id: '/settings/update-information',
    path: '/settings/update-information',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsChangePasswordRoute = SettingsChangePasswordRouteImport.update({
  id: '/settings/change-password',
  path: '/settings/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration/success',
  path: '/registration/success',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesUuidRoute = IssuesUuidRouteImport.update({
  id: '/issues/$uuid',
  path: '/issues/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const staticFaqRoute = staticFaqRouteImport.update({
  id: '/(static)/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const staticContactUsRoute = staticContactUsRouteImport.update({
  id: '/(static)/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const staticAboutUsRoute = staticAboutUsRouteImport.update({
  id: '/(static)/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationVolunteerLayoutRoute =
  RegistrationVolunteerLayoutRouteImport.update({
    id: '/registration/volunteer',
    path: '/registration/volunteer',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesNewIndexRoute = IssuesNewIndexRouteImport.update({
  id: '/issues/new/',
  path: '/issues/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const staticLegalIndexRoute = staticLegalIndexRouteImport.update({
  id: '/(static)/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerUploadMissingMediaUuidRoute =
  VolunteerUploadMissingMediaUuidRouteImport.update({
    id: '/volunteer/upload-missing-media/$uuid',
    path: '/volunteer/upload-missing-media/$uuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrationVolunteerUploadProfilePictureRoute =
  RegistrationVolunteerUploadProfilePictureRouteImport.update({
    id: '/upload-profile-picture',
    path: '/upload-profile-picture',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerSetPasswordRoute =
  RegistrationVolunteerSetPasswordRouteImport.update({
    id: '/set-password',
    path: '/set-password',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerSelectIdTypeRoute =
  RegistrationVolunteerSelectIdTypeRouteImport.update({
    id: '/select-id-type',
    path: '/select-id-type',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerPersonalInformationRoute =
  RegistrationVolunteerPersonalInformationRouteImport.update({
    id: '/personal-information',
    path: '/personal-information',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerNidInformationRoute =
  RegistrationVolunteerNidInformationRouteImport.update({
    id: '/nid-information',
    path: '/nid-information',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerLocationInformationRoute =
  RegistrationVolunteerLocationInformationRouteImport.update({
    id: '/location-information',
    path: '/location-information',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const RegistrationVolunteerBrnInformationRoute =
  RegistrationVolunteerBrnInformationRouteImport.update({
    id: '/brn-information',
    path: '/brn-information',
    getParentRoute: () => RegistrationVolunteerLayoutRoute,
  } as any)
const staticLegalWhyWeRequireIdDocumentsRoute =
  staticLegalWhyWeRequireIdDocumentsRouteImport.update({
    id: '/(static)/legal/why-we-require-id-documents',
    path: '/legal/why-we-require-id-documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const staticLegalTermsAndConditionsRoute =
  staticLegalTermsAndConditionsRouteImport.update({
    id: '/(static)/legal/terms-and-conditions',
    path: '/legal/terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const staticLegalPrivacyPolicyRoute =
  staticLegalPrivacyPolicyRouteImport.update({
    id: '/(static)/legal/privacy-policy',
    path: '/legal/privacy-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesNewLostAndFoundLayoutRoute =
  IssuesNewLostAndFoundLayoutRouteImport.update({
    id: '/issues/new/lost-and-found',
    path: '/issues/new/lost-and-found',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesNewBloodDonationLayoutRoute =
  IssuesNewBloodDonationLayoutRouteImport.update({
    id: '/issues/new/blood-donation',
    path: '/issues/new/blood-donation',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuesNewLostAndFoundAddMoreInformationRoute =
  IssuesNewLostAndFoundAddMoreInformationRouteImport.update({
    id: '/add-more-information',
    path: '/add-more-information',
    getParentRoute: () => IssuesNewLostAndFoundLayoutRoute,
  } as any)
const IssuesNewLostAndFoundAddImagesRoute =
  IssuesNewLostAndFoundAddImagesRouteImport.update({
    id: '/add-images',
    path: '/add-images',
    getParentRoute: () => IssuesNewLostAndFoundLayoutRoute,
  } as any)
const IssuesNewLostAndFoundAddContactInformationRoute =
  IssuesNewLostAndFoundAddContactInformationRouteImport.update({
    id: '/add-contact-information',
    path: '/add-contact-information',
    getParentRoute: () => IssuesNewLostAndFoundLayoutRoute,
  } as any)
const IssuesNewLostAndFoundAddBasicInformationRoute =
  IssuesNewLostAndFoundAddBasicInformationRouteImport.update({
    id: '/add-basic-information',
    path: '/add-basic-information',
    getParentRoute: () => IssuesNewLostAndFoundLayoutRoute,
  } as any)
const IssuesNewBloodDonationAddLocationInformationRoute =
  IssuesNewBloodDonationAddLocationInformationRouteImport.update({
    id: '/add-location-information',
    path: '/add-location-information',
    getParentRoute: () => IssuesNewBloodDonationLayoutRoute,
  } as any)
const IssuesNewBloodDonationAddContactInformationRoute =
  IssuesNewBloodDonationAddContactInformationRouteImport.update({
    id: '/add-contact-information',
    path: '/add-contact-information',
    getParentRoute: () => IssuesNewBloodDonationLayoutRoute,
  } as any)
const IssuesNewBloodDonationAddBasicInformationRoute =
  IssuesNewBloodDonationAddBasicInformationRouteImport.update({
    id: '/add-basic-information',
    path: '/add-basic-information',
    getParentRoute: () => IssuesNewBloodDonationLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/registration/volunteer': typeof RegistrationVolunteerLayoutRouteWithChildren
  '/about-us': typeof staticAboutUsRoute
  '/contact-us': typeof staticContactUsRoute
  '/faq': typeof staticFaqRoute
  '/issues/$uuid': typeof IssuesUuidRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/update-information': typeof SettingsUpdateInformationRoute
  '/team/$uuid': typeof TeamUuidRoute
  '/team/create': typeof TeamCreateRoute
  '/volunteer/$uuid': typeof VolunteerUuidRoute
  '/': typeof staticIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/login': typeof LoginIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/issues/new/blood-donation': typeof IssuesNewBloodDonationLayoutRouteWithChildren
  '/issues/new/lost-and-found': typeof IssuesNewLostAndFoundLayoutRouteWithChildren
  '/legal/privacy-policy': typeof staticLegalPrivacyPolicyRoute
  '/legal/terms-and-conditions': typeof staticLegalTermsAndConditionsRoute
  '/legal/why-we-require-id-documents': typeof staticLegalWhyWeRequireIdDocumentsRoute
  '/registration/volunteer/brn-information': typeof RegistrationVolunteerBrnInformationRoute
  '/registration/volunteer/location-information': typeof RegistrationVolunteerLocationInformationRoute
  '/registration/volunteer/nid-information': typeof RegistrationVolunteerNidInformationRoute
  '/registration/volunteer/personal-information': typeof RegistrationVolunteerPersonalInformationRoute
  '/registration/volunteer/select-id-type': typeof RegistrationVolunteerSelectIdTypeRoute
  '/registration/volunteer/set-password': typeof RegistrationVolunteerSetPasswordRoute
  '/registration/volunteer/upload-profile-picture': typeof RegistrationVolunteerUploadProfilePictureRoute
  '/volunteer/upload-missing-media/$uuid': typeof VolunteerUploadMissingMediaUuidRoute
  '/legal': typeof staticLegalIndexRoute
  '/issues/new': typeof IssuesNewIndexRoute
  '/issues/new/blood-donation/add-basic-information': typeof IssuesNewBloodDonationAddBasicInformationRoute
  '/issues/new/blood-donation/add-contact-information': typeof IssuesNewBloodDonationAddContactInformationRoute
  '/issues/new/blood-donation/add-location-information': typeof IssuesNewBloodDonationAddLocationInformationRoute
  '/issues/new/lost-and-found/add-basic-information': typeof IssuesNewLostAndFoundAddBasicInformationRoute
  '/issues/new/lost-and-found/add-contact-information': typeof IssuesNewLostAndFoundAddContactInformationRoute
  '/issues/new/lost-and-found/add-images': typeof IssuesNewLostAndFoundAddImagesRoute
  '/issues/new/lost-and-found/add-more-information': typeof IssuesNewLostAndFoundAddMoreInformationRoute
}
export interface FileRoutesByTo {
  '/registration/volunteer': typeof RegistrationVolunteerLayoutRouteWithChildren
  '/about-us': typeof staticAboutUsRoute
  '/contact-us': typeof staticContactUsRoute
  '/faq': typeof staticFaqRoute
  '/issues/$uuid': typeof IssuesUuidRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/update-information': typeof SettingsUpdateInformationRoute
  '/team/$uuid': typeof TeamUuidRoute
  '/team/create': typeof TeamCreateRoute
  '/volunteer/$uuid': typeof VolunteerUuidRoute
  '/': typeof staticIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/login': typeof LoginIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/issues/new/blood-donation': typeof IssuesNewBloodDonationLayoutRouteWithChildren
  '/issues/new/lost-and-found': typeof IssuesNewLostAndFoundLayoutRouteWithChildren
  '/legal/privacy-policy': typeof staticLegalPrivacyPolicyRoute
  '/legal/terms-and-conditions': typeof staticLegalTermsAndConditionsRoute
  '/legal/why-we-require-id-documents': typeof staticLegalWhyWeRequireIdDocumentsRoute
  '/registration/volunteer/brn-information': typeof RegistrationVolunteerBrnInformationRoute
  '/registration/volunteer/location-information': typeof RegistrationVolunteerLocationInformationRoute
  '/registration/volunteer/nid-information': typeof RegistrationVolunteerNidInformationRoute
  '/registration/volunteer/personal-information': typeof RegistrationVolunteerPersonalInformationRoute
  '/registration/volunteer/select-id-type': typeof RegistrationVolunteerSelectIdTypeRoute
  '/registration/volunteer/set-password': typeof RegistrationVolunteerSetPasswordRoute
  '/registration/volunteer/upload-profile-picture': typeof RegistrationVolunteerUploadProfilePictureRoute
  '/volunteer/upload-missing-media/$uuid': typeof VolunteerUploadMissingMediaUuidRoute
  '/legal': typeof staticLegalIndexRoute
  '/issues/new': typeof IssuesNewIndexRoute
  '/issues/new/blood-donation/add-basic-information': typeof IssuesNewBloodDonationAddBasicInformationRoute
  '/issues/new/blood-donation/add-contact-information': typeof IssuesNewBloodDonationAddContactInformationRoute
  '/issues/new/blood-donation/add-location-information': typeof IssuesNewBloodDonationAddLocationInformationRoute
  '/issues/new/lost-and-found/add-basic-information': typeof IssuesNewLostAndFoundAddBasicInformationRoute
  '/issues/new/lost-and-found/add-contact-information': typeof IssuesNewLostAndFoundAddContactInformationRoute
  '/issues/new/lost-and-found/add-images': typeof IssuesNewLostAndFoundAddImagesRoute
  '/issues/new/lost-and-found/add-more-information': typeof IssuesNewLostAndFoundAddMoreInformationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/registration/volunteer': typeof RegistrationVolunteerLayoutRouteWithChildren
  '/(static)/about-us': typeof staticAboutUsRoute
  '/(static)/contact-us': typeof staticContactUsRoute
  '/(static)/faq': typeof staticFaqRoute
  '/issues/$uuid': typeof IssuesUuidRoute
  '/registration/success': typeof RegistrationSuccessRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/settings/update-information': typeof SettingsUpdateInformationRoute
  '/team/$uuid': typeof TeamUuidRoute
  '/team/create': typeof TeamCreateRoute
  '/volunteer/$uuid': typeof VolunteerUuidRoute
  '/(static)/': typeof staticIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/issues/new/blood-donation': typeof IssuesNewBloodDonationLayoutRouteWithChildren
  '/issues/new/lost-and-found': typeof IssuesNewLostAndFoundLayoutRouteWithChildren
  '/(static)/legal/privacy-policy': typeof staticLegalPrivacyPolicyRoute
  '/(static)/legal/terms-and-conditions': typeof staticLegalTermsAndConditionsRoute
  '/(static)/legal/why-we-require-id-documents': typeof staticLegalWhyWeRequireIdDocumentsRoute
  '/registration/volunteer/brn-information': typeof RegistrationVolunteerBrnInformationRoute
  '/registration/volunteer/location-information': typeof RegistrationVolunteerLocationInformationRoute
  '/registration/volunteer/nid-information': typeof RegistrationVolunteerNidInformationRoute
  '/registration/volunteer/personal-information': typeof RegistrationVolunteerPersonalInformationRoute
  '/registration/volunteer/select-id-type': typeof RegistrationVolunteerSelectIdTypeRoute
  '/registration/volunteer/set-password': typeof RegistrationVolunteerSetPasswordRoute
  '/registration/volunteer/upload-profile-picture': typeof RegistrationVolunteerUploadProfilePictureRoute
  '/volunteer/upload-missing-media/$uuid': typeof VolunteerUploadMissingMediaUuidRoute
  '/(static)/legal/': typeof staticLegalIndexRoute
  '/issues/new/': typeof IssuesNewIndexRoute
  '/issues/new/blood-donation/add-basic-information': typeof IssuesNewBloodDonationAddBasicInformationRoute
  '/issues/new/blood-donation/add-contact-information': typeof IssuesNewBloodDonationAddContactInformationRoute
  '/issues/new/blood-donation/add-location-information': typeof IssuesNewBloodDonationAddLocationInformationRoute
  '/issues/new/lost-and-found/add-basic-information': typeof IssuesNewLostAndFoundAddBasicInformationRoute
  '/issues/new/lost-and-found/add-contact-information': typeof IssuesNewLostAndFoundAddContactInformationRoute
  '/issues/new/lost-and-found/add-images': typeof IssuesNewLostAndFoundAddImagesRoute
  '/issues/new/lost-and-found/add-more-information': typeof IssuesNewLostAndFoundAddMoreInformationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/registration/volunteer'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/issues/$uuid'
    | '/registration/success'
    | '/settings/change-password'
    | '/settings/update-information'
    | '/team/$uuid'
    | '/team/create'
    | '/volunteer/$uuid'
    | '/'
    | '/issues'
    | '/login'
    | '/registration'
    | '/issues/new/blood-donation'
    | '/issues/new/lost-and-found'
    | '/legal/privacy-policy'
    | '/legal/terms-and-conditions'
    | '/legal/why-we-require-id-documents'
    | '/registration/volunteer/brn-information'
    | '/registration/volunteer/location-information'
    | '/registration/volunteer/nid-information'
    | '/registration/volunteer/personal-information'
    | '/registration/volunteer/select-id-type'
    | '/registration/volunteer/set-password'
    | '/registration/volunteer/upload-profile-picture'
    | '/volunteer/upload-missing-media/$uuid'
    | '/legal'
    | '/issues/new'
    | '/issues/new/blood-donation/add-basic-information'
    | '/issues/new/blood-donation/add-contact-information'
    | '/issues/new/blood-donation/add-location-information'
    | '/issues/new/lost-and-found/add-basic-information'
    | '/issues/new/lost-and-found/add-contact-information'
    | '/issues/new/lost-and-found/add-images'
    | '/issues/new/lost-and-found/add-more-information'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/registration/volunteer'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/issues/$uuid'
    | '/registration/success'
    | '/settings/change-password'
    | '/settings/update-information'
    | '/team/$uuid'
    | '/team/create'
    | '/volunteer/$uuid'
    | '/'
    | '/issues'
    | '/login'
    | '/registration'
    | '/issues/new/blood-donation'
    | '/issues/new/lost-and-found'
    | '/legal/privacy-policy'
    | '/legal/terms-and-conditions'
    | '/legal/why-we-require-id-documents'
    | '/registration/volunteer/brn-information'
    | '/registration/volunteer/location-information'
    | '/registration/volunteer/nid-information'
    | '/registration/volunteer/personal-information'
    | '/registration/volunteer/select-id-type'
    | '/registration/volunteer/set-password'
    | '/registration/volunteer/upload-profile-picture'
    | '/volunteer/upload-missing-media/$uuid'
    | '/legal'
    | '/issues/new'
    | '/issues/new/blood-donation/add-basic-information'
    | '/issues/new/blood-donation/add-contact-information'
    | '/issues/new/blood-donation/add-location-information'
    | '/issues/new/lost-and-found/add-basic-information'
    | '/issues/new/lost-and-found/add-contact-information'
    | '/issues/new/lost-and-found/add-images'
    | '/issues/new/lost-and-found/add-more-information'
  id:
    | '__root__'
    | '/registration/volunteer'
    | '/(static)/about-us'
    | '/(static)/contact-us'
    | '/(static)/faq'
    | '/issues/$uuid'
    | '/registration/success'
    | '/settings/change-password'
    | '/settings/update-information'
    | '/team/$uuid'
    | '/team/create'
    | '/volunteer/$uuid'
    | '/(static)/'
    | '/issues/'
    | '/login/'
    | '/registration/'
    | '/issues/new/blood-donation'
    | '/issues/new/lost-and-found'
    | '/(static)/legal/privacy-policy'
    | '/(static)/legal/terms-and-conditions'
    | '/(static)/legal/why-we-require-id-documents'
    | '/registration/volunteer/brn-information'
    | '/registration/volunteer/location-information'
    | '/registration/volunteer/nid-information'
    | '/registration/volunteer/personal-information'
    | '/registration/volunteer/select-id-type'
    | '/registration/volunteer/set-password'
    | '/registration/volunteer/upload-profile-picture'
    | '/volunteer/upload-missing-media/$uuid'
    | '/(static)/legal/'
    | '/issues/new/'
    | '/issues/new/blood-donation/add-basic-information'
    | '/issues/new/blood-donation/add-contact-information'
    | '/issues/new/blood-donation/add-location-information'
    | '/issues/new/lost-and-found/add-basic-information'
    | '/issues/new/lost-and-found/add-contact-information'
    | '/issues/new/lost-and-found/add-images'
    | '/issues/new/lost-and-found/add-more-information'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RegistrationVolunteerLayoutRoute: typeof RegistrationVolunteerLayoutRouteWithChildren
  staticAboutUsRoute: typeof staticAboutUsRoute
  staticContactUsRoute: typeof staticContactUsRoute
  staticFaqRoute: typeof staticFaqRoute
  IssuesUuidRoute: typeof IssuesUuidRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  SettingsChangePasswordRoute: typeof SettingsChangePasswordRoute
  SettingsUpdateInformationRoute: typeof SettingsUpdateInformationRoute
  TeamUuidRoute: typeof TeamUuidRoute
  TeamCreateRoute: typeof TeamCreateRoute
  VolunteerUuidRoute: typeof VolunteerUuidRoute
  staticIndexRoute: typeof staticIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  IssuesNewBloodDonationLayoutRoute: typeof IssuesNewBloodDonationLayoutRouteWithChildren
  IssuesNewLostAndFoundLayoutRoute: typeof IssuesNewLostAndFoundLayoutRouteWithChildren
  staticLegalPrivacyPolicyRoute: typeof staticLegalPrivacyPolicyRoute
  staticLegalTermsAndConditionsRoute: typeof staticLegalTermsAndConditionsRoute
  staticLegalWhyWeRequireIdDocumentsRoute: typeof staticLegalWhyWeRequireIdDocumentsRoute
  VolunteerUploadMissingMediaUuidRoute: typeof VolunteerUploadMissingMediaUuidRoute
  staticLegalIndexRoute: typeof staticLegalIndexRoute
  IssuesNewIndexRoute: typeof IssuesNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/$uuid': {
      id: '/volunteer/$uuid'
      path: '/volunteer/$uuid'
      fullPath: '/volunteer/$uuid'
      preLoaderRoute: typeof VolunteerUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/create': {
      id: '/team/create'
      path: '/team/create'
      fullPath: '/team/create'
      preLoaderRoute: typeof TeamCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$uuid': {
      id: '/team/$uuid'
      path: '/team/$uuid'
      fullPath: '/team/$uuid'
      preLoaderRoute: typeof TeamUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/update-information': {
      id: '/settings/update-information'
      path: '/settings/update-information'
      fullPath: '/settings/update-information'
      preLoaderRoute: typeof SettingsUpdateInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/change-password': {
      id: '/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof SettingsChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/success': {
      id: '/registration/success'
      path: '/registration/success'
      fullPath: '/registration/success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$uuid': {
      id: '/issues/$uuid'
      path: '/issues/$uuid'
      fullPath: '/issues/$uuid'
      preLoaderRoute: typeof IssuesUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/faq': {
      id: '/(static)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof staticFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/contact-us': {
      id: '/(static)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof staticContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/about-us': {
      id: '/(static)/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof staticAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/volunteer': {
      id: '/registration/volunteer'
      path: '/registration/volunteer'
      fullPath: '/registration/volunteer'
      preLoaderRoute: typeof RegistrationVolunteerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new/': {
      id: '/issues/new/'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/legal/': {
      id: '/(static)/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof staticLegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/upload-missing-media/$uuid': {
      id: '/volunteer/upload-missing-media/$uuid'
      path: '/volunteer/upload-missing-media/$uuid'
      fullPath: '/volunteer/upload-missing-media/$uuid'
      preLoaderRoute: typeof VolunteerUploadMissingMediaUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/volunteer/upload-profile-picture': {
      id: '/registration/volunteer/upload-profile-picture'
      path: '/upload-profile-picture'
      fullPath: '/registration/volunteer/upload-profile-picture'
      preLoaderRoute: typeof RegistrationVolunteerUploadProfilePictureRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/set-password': {
      id: '/registration/volunteer/set-password'
      path: '/set-password'
      fullPath: '/registration/volunteer/set-password'
      preLoaderRoute: typeof RegistrationVolunteerSetPasswordRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/select-id-type': {
      id: '/registration/volunteer/select-id-type'
      path: '/select-id-type'
      fullPath: '/registration/volunteer/select-id-type'
      preLoaderRoute: typeof RegistrationVolunteerSelectIdTypeRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/personal-information': {
      id: '/registration/volunteer/personal-information'
      path: '/personal-information'
      fullPath: '/registration/volunteer/personal-information'
      preLoaderRoute: typeof RegistrationVolunteerPersonalInformationRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/nid-information': {
      id: '/registration/volunteer/nid-information'
      path: '/nid-information'
      fullPath: '/registration/volunteer/nid-information'
      preLoaderRoute: typeof RegistrationVolunteerNidInformationRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/location-information': {
      id: '/registration/volunteer/location-information'
      path: '/location-information'
      fullPath: '/registration/volunteer/location-information'
      preLoaderRoute: typeof RegistrationVolunteerLocationInformationRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/registration/volunteer/brn-information': {
      id: '/registration/volunteer/brn-information'
      path: '/brn-information'
      fullPath: '/registration/volunteer/brn-information'
      preLoaderRoute: typeof RegistrationVolunteerBrnInformationRouteImport
      parentRoute: typeof RegistrationVolunteerLayoutRoute
    }
    '/(static)/legal/why-we-require-id-documents': {
      id: '/(static)/legal/why-we-require-id-documents'
      path: '/legal/why-we-require-id-documents'
      fullPath: '/legal/why-we-require-id-documents'
      preLoaderRoute: typeof staticLegalWhyWeRequireIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/legal/terms-and-conditions': {
      id: '/(static)/legal/terms-and-conditions'
      path: '/legal/terms-and-conditions'
      fullPath: '/legal/terms-and-conditions'
      preLoaderRoute: typeof staticLegalTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/legal/privacy-policy': {
      id: '/(static)/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof staticLegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new/lost-and-found': {
      id: '/issues/new/lost-and-found'
      path: '/issues/new/lost-and-found'
      fullPath: '/issues/new/lost-and-found'
      preLoaderRoute: typeof IssuesNewLostAndFoundLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new/blood-donation': {
      id: '/issues/new/blood-donation'
      path: '/issues/new/blood-donation'
      fullPath: '/issues/new/blood-donation'
      preLoaderRoute: typeof IssuesNewBloodDonationLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new/lost-and-found/add-more-information': {
      id: '/issues/new/lost-and-found/add-more-information'
      path: '/add-more-information'
      fullPath: '/issues/new/lost-and-found/add-more-information'
      preLoaderRoute: typeof IssuesNewLostAndFoundAddMoreInformationRouteImport
      parentRoute: typeof IssuesNewLostAndFoundLayoutRoute
    }
    '/issues/new/lost-and-found/add-images': {
      id: '/issues/new/lost-and-found/add-images'
      path: '/add-images'
      fullPath: '/issues/new/lost-and-found/add-images'
      preLoaderRoute: typeof IssuesNewLostAndFoundAddImagesRouteImport
      parentRoute: typeof IssuesNewLostAndFoundLayoutRoute
    }
    '/issues/new/lost-and-found/add-contact-information': {
      id: '/issues/new/lost-and-found/add-contact-information'
      path: '/add-contact-information'
      fullPath: '/issues/new/lost-and-found/add-contact-information'
      preLoaderRoute: typeof IssuesNewLostAndFoundAddContactInformationRouteImport
      parentRoute: typeof IssuesNewLostAndFoundLayoutRoute
    }
    '/issues/new/lost-and-found/add-basic-information': {
      id: '/issues/new/lost-and-found/add-basic-information'
      path: '/add-basic-information'
      fullPath: '/issues/new/lost-and-found/add-basic-information'
      preLoaderRoute: typeof IssuesNewLostAndFoundAddBasicInformationRouteImport
      parentRoute: typeof IssuesNewLostAndFoundLayoutRoute
    }
    '/issues/new/blood-donation/add-location-information': {
      id: '/issues/new/blood-donation/add-location-information'
      path: '/add-location-information'
      fullPath: '/issues/new/blood-donation/add-location-information'
      preLoaderRoute: typeof IssuesNewBloodDonationAddLocationInformationRouteImport
      parentRoute: typeof IssuesNewBloodDonationLayoutRoute
    }
    '/issues/new/blood-donation/add-contact-information': {
      id: '/issues/new/blood-donation/add-contact-information'
      path: '/add-contact-information'
      fullPath: '/issues/new/blood-donation/add-contact-information'
      preLoaderRoute: typeof IssuesNewBloodDonationAddContactInformationRouteImport
      parentRoute: typeof IssuesNewBloodDonationLayoutRoute
    }
    '/issues/new/blood-donation/add-basic-information': {
      id: '/issues/new/blood-donation/add-basic-information'
      path: '/add-basic-information'
      fullPath: '/issues/new/blood-donation/add-basic-information'
      preLoaderRoute: typeof IssuesNewBloodDonationAddBasicInformationRouteImport
      parentRoute: typeof IssuesNewBloodDonationLayoutRoute
    }
  }
}

interface RegistrationVolunteerLayoutRouteChildren {
  RegistrationVolunteerBrnInformationRoute: typeof RegistrationVolunteerBrnInformationRoute
  RegistrationVolunteerLocationInformationRoute: typeof RegistrationVolunteerLocationInformationRoute
  RegistrationVolunteerNidInformationRoute: typeof RegistrationVolunteerNidInformationRoute
  RegistrationVolunteerPersonalInformationRoute: typeof RegistrationVolunteerPersonalInformationRoute
  RegistrationVolunteerSelectIdTypeRoute: typeof RegistrationVolunteerSelectIdTypeRoute
  RegistrationVolunteerSetPasswordRoute: typeof RegistrationVolunteerSetPasswordRoute
  RegistrationVolunteerUploadProfilePictureRoute: typeof RegistrationVolunteerUploadProfilePictureRoute
}

const RegistrationVolunteerLayoutRouteChildren: RegistrationVolunteerLayoutRouteChildren =
  {
    RegistrationVolunteerBrnInformationRoute:
      RegistrationVolunteerBrnInformationRoute,
    RegistrationVolunteerLocationInformationRoute:
      RegistrationVolunteerLocationInformationRoute,
    RegistrationVolunteerNidInformationRoute:
      RegistrationVolunteerNidInformationRoute,
    RegistrationVolunteerPersonalInformationRoute:
      RegistrationVolunteerPersonalInformationRoute,
    RegistrationVolunteerSelectIdTypeRoute:
      RegistrationVolunteerSelectIdTypeRoute,
    RegistrationVolunteerSetPasswordRoute:
      RegistrationVolunteerSetPasswordRoute,
    RegistrationVolunteerUploadProfilePictureRoute:
      RegistrationVolunteerUploadProfilePictureRoute,
  }

const RegistrationVolunteerLayoutRouteWithChildren =
  RegistrationVolunteerLayoutRoute._addFileChildren(
    RegistrationVolunteerLayoutRouteChildren,
  )

interface IssuesNewBloodDonationLayoutRouteChildren {
  IssuesNewBloodDonationAddBasicInformationRoute: typeof IssuesNewBloodDonationAddBasicInformationRoute
  IssuesNewBloodDonationAddContactInformationRoute: typeof IssuesNewBloodDonationAddContactInformationRoute
  IssuesNewBloodDonationAddLocationInformationRoute: typeof IssuesNewBloodDonationAddLocationInformationRoute
}

const IssuesNewBloodDonationLayoutRouteChildren: IssuesNewBloodDonationLayoutRouteChildren =
  {
    IssuesNewBloodDonationAddBasicInformationRoute:
      IssuesNewBloodDonationAddBasicInformationRoute,
    IssuesNewBloodDonationAddContactInformationRoute:
      IssuesNewBloodDonationAddContactInformationRoute,
    IssuesNewBloodDonationAddLocationInformationRoute:
      IssuesNewBloodDonationAddLocationInformationRoute,
  }

const IssuesNewBloodDonationLayoutRouteWithChildren =
  IssuesNewBloodDonationLayoutRoute._addFileChildren(
    IssuesNewBloodDonationLayoutRouteChildren,
  )

interface IssuesNewLostAndFoundLayoutRouteChildren {
  IssuesNewLostAndFoundAddBasicInformationRoute: typeof IssuesNewLostAndFoundAddBasicInformationRoute
  IssuesNewLostAndFoundAddContactInformationRoute: typeof IssuesNewLostAndFoundAddContactInformationRoute
  IssuesNewLostAndFoundAddImagesRoute: typeof IssuesNewLostAndFoundAddImagesRoute
  IssuesNewLostAndFoundAddMoreInformationRoute: typeof IssuesNewLostAndFoundAddMoreInformationRoute
}

const IssuesNewLostAndFoundLayoutRouteChildren: IssuesNewLostAndFoundLayoutRouteChildren =
  {
    IssuesNewLostAndFoundAddBasicInformationRoute:
      IssuesNewLostAndFoundAddBasicInformationRoute,
    IssuesNewLostAndFoundAddContactInformationRoute:
      IssuesNewLostAndFoundAddContactInformationRoute,
    IssuesNewLostAndFoundAddImagesRoute: IssuesNewLostAndFoundAddImagesRoute,
    IssuesNewLostAndFoundAddMoreInformationRoute:
      IssuesNewLostAndFoundAddMoreInformationRoute,
  }

const IssuesNewLostAndFoundLayoutRouteWithChildren =
  IssuesNewLostAndFoundLayoutRoute._addFileChildren(
    IssuesNewLostAndFoundLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  RegistrationVolunteerLayoutRoute:
    RegistrationVolunteerLayoutRouteWithChildren,
  staticAboutUsRoute: staticAboutUsRoute,
  staticContactUsRoute: staticContactUsRoute,
  staticFaqRoute: staticFaqRoute,
  IssuesUuidRoute: IssuesUuidRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  SettingsChangePasswordRoute: SettingsChangePasswordRoute,
  SettingsUpdateInformationRoute: SettingsUpdateInformationRoute,
  TeamUuidRoute: TeamUuidRoute,
  TeamCreateRoute: TeamCreateRoute,
  VolunteerUuidRoute: VolunteerUuidRoute,
  staticIndexRoute: staticIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  IssuesNewBloodDonationLayoutRoute:
    IssuesNewBloodDonationLayoutRouteWithChildren,
  IssuesNewLostAndFoundLayoutRoute:
    IssuesNewLostAndFoundLayoutRouteWithChildren,
  staticLegalPrivacyPolicyRoute: staticLegalPrivacyPolicyRoute,
  staticLegalTermsAndConditionsRoute: staticLegalTermsAndConditionsRoute,
  staticLegalWhyWeRequireIdDocumentsRoute:
    staticLegalWhyWeRequireIdDocumentsRoute,
  VolunteerUploadMissingMediaUuidRoute: VolunteerUploadMissingMediaUuidRoute,
  staticLegalIndexRoute: staticLegalIndexRoute,
  IssuesNewIndexRoute: IssuesNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
